Update Rust protocol to get correct players when > 256
Austinb/GameQ pull request #536
Opened 2020-04-10 11:12 UTC by devu4

With servers over 256 players, the max_players and num_players fields show wrong number. This is because Source can only send 128*2 for player info.

 Rust creates keywords to save player count so use this instead of what's returned from source.

2020-04-10 11:12 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Austinb/GameQ/inspections/a4f7af94-6ed0-4e87-9a75-53f638a35d29) was created.

2020-04-10 11:16 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Austinb/GameQ/inspections/88a802ee-267a-45d9-9d2a-4b05dcc10c53) was created.

2020-04-10 11:20 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Austinb/GameQ/inspections/a4f7af94-6ed0-4e87-9a75-53f638a35d29) completed: **1 updated code elements**

2020-04-10 11:22 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Austinb/GameQ/inspections/88a802ee-267a-45d9-9d2a-4b05dcc10c53) completed: **1 updated code elements**

2020-04-14 04:37 UTC, Austinb commented
Need a test snapshot from two servers to add to this so it can be run against unit tests.  If you don't want to do it send me a list of servers that regularly have that many users and I can pull the tests in.

2020-04-14 04:39 UTC, Austinb requested changes
Needs unit tests with at least two servers over the 256 player threshold.

2020-04-15 18:13 UTC, devu4 commented
1. 208.103.169.73:28028, slots count shows 44 when its max_players should be 300
2. 31.186.250.30:28062, max_players should again be 300 and usually has online players > 256

Sorry, I couldn't do the unit tests for you.

2022-05-22 23:44 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Austinb/GameQ/inspections/6c9da6c3-49bc-4527-a227-ec7fba10d605) was created.

2022-05-22 23:55 UTC, closed without merging