Added New Protocols and Respective Tests
Austinb/GameQ pull request #545
Opened 2020-04-26 19:14 UTC by uilson

Added protocols and respective tests for the following games:

Call of Duty: Modern Warfare  2
Doom 3
Hidden & Dangerous 2  ( closes #538 )
Halo: Combat Evolved
Hell Let Loose ( closes #542 )
Kingpin
Mafia 2 Multiplayer
Miscreated
OpenTTD ( closes #519 )
Post Scriptum ( closes #532 )
Quake 4
rFactor 2 ( closes #528 )

Also updated Atlas test class to correct the PHPUnit error if a query port used was different from the  stock port logic.

Mordhau (closes #485 ) was also added in a previous commit.

2020-04-26 19:14 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Austinb/GameQ/inspections/2501d960-e81d-464d-a961-41a0710d37db) was created.

2020-04-26 19:17 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Austinb/GameQ/inspections/2501d960-e81d-464d-a961-41a0710d37db) completed: **23 updated code elements**

2020-05-03 18:34 UTC, Austinb requested changes
Last test run on this failed.  One is due to a hostname but the others need to be looked at.  Please see https://travis-ci.org/github/Austinb/GameQ/builds/679814262 for the last specific build for this PR.  

Also merge in v3 so you can get the bad hostname fix for crysis.

2020-05-05 12:30 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Austinb/GameQ/inspections/2e29eac2-e909-4c97-a79e-e3de1107d88c) was created.

2020-05-05 12:33 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Austinb/GameQ/inspections/2e29eac2-e909-4c97-a79e-e3de1107d88c) completed: **23 updated code elements**

2020-05-05 14:20 UTC, uilson commented
> Last test run on this failed. One is due to a hostname but the others need to be looked at. Please see https://travis-ci.org/github/Austinb/GameQ/builds/679814262 for the last specific build for this PR.
> 
> Also merge in v3 so you can get the bad hostname fix for crysis.

I found the problem. its related to the last changes you made to the [Quake3.php](https://github.com/Austinb/GameQ/commit/ee68c80abe90ad1bed46277ec975403e95cc9316#diff-4499419667425f018dc4480fe4ff5507).

For some reason I had a previous version on my ubuntu test machine, and it queried the Codmw2 without problems, but with the new version it says 

> GameQ\Protocols\Quake3::processResponse response type '' is not valid

Meaning, it tries to parse the response, but, when the time comes to parse the players, it breaks because it does not see the info the way it is requested on the new version of "Quake3.php". 

On the previous version it requested the "\x0a" and them parsed the players, but now it fails because he cant see the players correctly.

2020-05-09 00:47 UTC, uilson commented
Going to finalize including of the old version of the  players processing function in the protocol, including a change to ignore the last user that is returned as empty, and push the changes. 

Will fix it for now, but later the main quake3 protocol may need to be changed, because if it fails in this game, it probably will fail in others, so later this may also need to be changed to remove the players processing from it.

2022-05-23 20:10 UTC, closed without merging