Add Pterodactyl Games
Austinb/GameQ pull request #655
Opened 2022-08-27 19:43 UTC by Erani0

Add Barotrauma
Add Black Mesa
Add Citadel Forged with fire
Add Half Life
Add Fistful of Frags
Add Modiverse
Add No More Room in Hell
Add Open Fortress
Add Stormworks Build and Rescue
Add Sven Co-op

2022-08-27 19:43 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Austinb/GameQ/inspections/00dd5fae-7b9f-4ab8-b8d1-bf7b52546a81) was created.

2022-08-27 20:18 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Austinb/GameQ/inspections/00dd5fae-7b9f-4ab8-b8d1-bf7b52546a81) completed: **10 updated code elements**

2022-08-28 11:26 UTC, bumbummen99 commented
Can you sign the commit with git commit --amend --signoff -S please?

2022-08-28 12:26 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Austinb/GameQ/inspections/55fd6ee6-01d5-4378-bf9a-c7b88e4e7ad5) was created.

2022-08-28 12:59 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Austinb/GameQ/inspections/55fd6ee6-01d5-4378-bf9a-c7b88e4e7ad5) completed: **No new issues**

2022-08-28 13:53 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Austinb/GameQ/inspections/9ef79a1e-e98a-4869-9750-c29d722bddfb) was created.

2022-08-28 13:58 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Austinb/GameQ/inspections/69c186ea-70ad-4437-be6c-8e3690c1c2d3) was created.

2022-08-28 14:07 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Austinb/GameQ/inspections/250807c8-0cb8-4af8-934a-de66d6a9e82d) was created.

2022-08-28 14:37 UTC, bumbummen99 requested changes
Please check the review comments, some tests also look strange

2022-08-28 14:37 UTC, bumbummen99 commented on src/GameQ/Protocols/Blackmesa.php
> +    /**
Please remove unused code

2022-08-28 14:37 UTC, bumbummen99 commented on src/GameQ/Protocols/Citadel.php
> +    /**
Please remove unused code

2022-08-28 14:37 UTC, bumbummen99 commented on tests/Protocols/Barotrauma.php
> +class Barotrauma extends Source
This does not look like a test

2022-08-28 14:37 UTC, bumbummen99 commented on tests/Protocols/Blackmesa.php
> +class Blackmesa extends Source
This does not look like a test

2022-08-28 14:37 UTC, bumbummen99 commented on tests/Protocols/Citadel.php
> +class Citadel extends Source
This does not look like a test

2022-08-28 14:37 UTC, bumbummen99 commented on tests/Protocols/Fof.php
> +        \GameQ\Tests\MockDNS::mockHosts([
Please remove unneccesary code.
Only required if you use hostname in the query config

2022-08-28 14:37 UTC, bumbummen99 commented on tests/Protocols/Hl1.php
> +        \GameQ\Tests\MockDNS::mockHosts([
Please remove unneccesary code.
Only required if you use hostname in the query config

2022-08-28 14:37 UTC, bumbummen99 commented on tests/Protocols/Modiverse.php
> +        \GameQ\Tests\MockDNS::mockHosts([
Please remove unneccesary code.
Only required if you use hostname in the query config

2022-08-28 14:37 UTC, bumbummen99 commented on tests/Protocols/Nmrih.php
> +        \GameQ\Tests\MockDNS::mockHosts([
Please remove unneccesary code.
Only required if you use hostname in the query config

2022-08-28 14:37 UTC, bumbummen99 commented on tests/Protocols/Of.php
> +        \GameQ\Tests\MockDNS::mockHosts([
Please remove unneccesary code.
Only required if you use hostname in the query config

2022-08-28 14:37 UTC, bumbummen99 commented on tests/Protocols/Sco.php
> +        \GameQ\Tests\MockDNS::mockHosts([
Please remove unneccesary code.
Only required if you use hostname in the query config

2022-08-28 14:37 UTC, bumbummen99 commented on tests/Protocols/Stormworks.php
> +        \GameQ\Tests\MockDNS::mockHosts([
Please remove unneccesary code.
Only required if you use hostname in the query config

2022-08-28 14:40 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Austinb/GameQ/inspections/250807c8-0cb8-4af8-934a-de66d6a9e82d) completed: **12 updated code elements**

2022-08-28 15:30 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/Austinb/GameQ/inspections/3b6754f2-14dd-4e6b-889d-4680d636bd76) was created.

2022-08-28 15:34 UTC, Erani0 commented
the testfile from Add No More Room in Hell not correct

2022-08-28 16:05 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/Austinb/GameQ/inspections/3b6754f2-14dd-4e6b-889d-4680d636bd76) completed: **No new issues**

2022-08-28 16:06 UTC, bumbummen99 approved these changes
LGTM

2022-08-28 16:06 UTC, merged